vich_uploader:
    db_driver: orm

    mappings:
        dishes_images:
            uri_prefix: '%dishes_images%'
            upload_destination: '%kernel.project_dir%/public%dishes_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        meals_images:
            uri_prefix: '%meals_images%'
            upload_destination: '%kernel.project_dir%/public%meals_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
